import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const spacer = localFont({
  src: "./fonts/Spacer36.otf",
  variable: "--font-spacer",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spacer.variable} antialiased`}>
        <Providers>
          {children}
          <ToastContainer />
        </Providers>
      </body>

    </html>
  );
}